import type MarkdownIt from 'markdown-it';
import type Token from 'markdown-it/lib/token.mjs';

const PREAMBLE = `// Generated by md-share
#set page(paper: "us-letter")
#set text(size: 11pt)

`;

const HEADING_MARKUP: Record<string, string> = {
  h1: '=',
  h2: '==',
  h3: '===',
  h4: '====',
};

const KIND_WORD: Record<string, string> = {
  fig: 'Figure',
  tbl: 'Table',
  eq: 'Equation',
};

export const escapeTypst = (s: string): string => {
  let out = '';
  for (const ch of s) {
    switch (ch) {
      case '\\':
      case '#':
      case '@':
      case '`':
      case '<':
      case '>':
      case '$':
      case '*':
      case '_':
      case '~':
      case '"':
      case '[':
      case ']':
        out += `\\${ch}`;
        break;
      default:
        out += ch;
    }
  }
  return out;
};

const getAttr = (token: Token, name: string): string | undefined =>
  token.attrs?.find(([k]) => k === name)?.[1];

interface TableState {
  cols: number;
  cells: string[];
}

interface Context {
  unknown: Set<string>;
  tableState: TableState | null;
  listStack: ('ul' | 'ol')[];
}

// markdown-it emits inline tokens with non-null children (possibly empty).
const renderInline = (children: Token[], ctx: Context): string => {
  let out = '';
  for (const t of children) {
    switch (t.type) {
      case 'text':
        out += escapeTypst(t.content);
        break;
      case 'softbreak':
        out += ' ';
        break;
      case 'hardbreak':
        out += ' \\\n';
        break;
      case 'strong_open':
      case 'strong_close':
        out += '*';
        break;
      case 'em_open':
      case 'em_close':
        out += '_';
        break;
      case 'code_inline':
        out += `#raw(${JSON.stringify(t.content)})`;
        break;
      case 'link_open': {
        out += `#link(${JSON.stringify(getAttr(t, 'href')!)})[`;
        break;
      }
      case 'link_close':
        out += ']';
        break;
      case 'image': {
        const src = getAttr(t, 'src')!;
        out += `#figure(image(${JSON.stringify(src)}), caption: [${escapeTypst(t.content)}])`;
        break;
      }
      case 'math_inline':
        out += `$${t.content}$`;
        break;
      case 'pandoc_cite':
        out += `@${t.content}`;
        break;
      case 'xref': {
        const meta = t.meta as { kind: 'fig' | 'tbl' | 'eq'; resolved: boolean };
        const word = KIND_WORD[meta.kind]!;
        if (!meta.resolved) out += `${word} ?${escapeTypst(t.content)}?`;
        else out += `@${meta.kind}-${t.content}`;
        break;
      }
      case 'html_inline':
        break;
      default:
        ctx.unknown.add(t.type);
    }
  }
  return out;
};

// markdown-it guarantees matched open/close pairs at the same level.
const skipTo = (tokens: Token[], from: number, closeType: string, depth: number): number => {
  let j = from;
  while (tokens[j]!.type !== closeType || tokens[j]!.level !== depth) j++;
  return j;
};

const renderTokens = (tokens: Token[], ctx: Context): string => {
  let out = '';
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i]!;
    switch (t.type) {
      case 'heading_open': {
        const mark = HEADING_MARKUP[t.tag] ?? '====';
        const content = renderInline(tokens[i + 1]!.children!, ctx);
        out += `${mark} ${content}\n\n`;
        i += 2;
        break;
      }
      case 'paragraph_open': {
        const content = renderInline(tokens[i + 1]!.children!, ctx);
        if (content.length) out += `${content}\n\n`;
        i += 2;
        break;
      }
      case 'bullet_list_open':
        ctx.listStack.push('ul');
        break;
      case 'ordered_list_open':
        ctx.listStack.push('ol');
        break;
      case 'bullet_list_close':
      case 'ordered_list_close':
        ctx.listStack.pop();
        if (ctx.listStack.length === 0) out += '\n';
        break;
      case 'list_item_open': {
        // listStack is always non-empty here — a list_item_open is only emitted inside a list
        const kind = ctx.listStack[ctx.listStack.length - 1]!;
        const indent = '  '.repeat(ctx.listStack.length - 1);
        const marker = kind === 'ul' ? '-' : '+';
        const end = skipTo(tokens, i + 1, 'list_item_close', t.level);
        const body = renderTokens(tokens.slice(i + 1, end), ctx).trimEnd();
        out += `${indent}${marker} ${body}\n`;
        i = end;
        break;
      }
      case 'fence':
      case 'code_block': {
        const lang = t.info.trim();
        const content = t.content.replace(/\n$/, '');
        out += `\`\`\`${lang}\n${content}\n\`\`\`\n\n`;
        break;
      }
      case 'math_block':
        out += `$ ${t.content} $\n\n`;
        break;
      case 'blockquote_open': {
        const end = skipTo(tokens, i + 1, 'blockquote_close', t.level);
        const body = renderTokens(tokens.slice(i + 1, end), ctx).trimEnd();
        out += `#quote(block: true)[${body}]\n\n`;
        i = end;
        break;
      }
      case 'hr':
        out += '#line(length: 100%)\n\n';
        break;
      case 'table_open':
        ctx.tableState = { cols: 0, cells: [] };
        break;
      case 'th_open':
      case 'td_open': {
        const cell = renderInline(tokens[i + 1]!.children!, ctx);
        const ts = ctx.tableState!;
        if (t.type === 'th_open') {
          ts.cells.push(`[*${cell}*]`);
          ts.cols++;
        } else {
          ts.cells.push(`[${cell}]`);
        }
        i += 2;
        break;
      }
      case 'table_close': {
        const ts = ctx.tableState!;
        out += `#table(\n  columns: ${ts.cols},\n  ${ts.cells.join(', ')},\n)\n\n`;
        ctx.tableState = null;
        break;
      }
      case 'html_block':
        break;
      case 'inline': {
        const content = renderInline(t.children!, ctx);
        if (content.length) out += `${content}\n\n`;
        break;
      }
      case 'footnote_block_open':
        i = skipTo(tokens, i + 1, 'footnote_block_close', t.level);
        break;
      case 'thead_open':
      case 'thead_close':
      case 'tbody_open':
      case 'tbody_close':
      case 'tr_open':
      case 'tr_close':
        break;
      default:
        ctx.unknown.add(t.type);
    }
  }
  return out;
};

export interface TypstResult {
  content: string;
  unknownTypes: Set<string>;
}

export const markdownToTypstWithMeta = (source: string, md: MarkdownIt): TypstResult => {
  const tokens = md.parse(source, {});
  const ctx: Context = { unknown: new Set(), tableState: null, listStack: [] };
  const body = renderTokens(tokens, ctx);
  return { content: `${PREAMBLE}${body}`, unknownTypes: ctx.unknown };
};

export const markdownToTypst = (source: string, md: MarkdownIt): string =>
  markdownToTypstWithMeta(source, md).content;
