import hljs from 'highlight.js';
import katex from 'katex';
import { describe, expect, it } from 'vitest';
import { buildMD, createFlavorDeps } from '../src/flavors.ts';
import { parseFrontmatter } from '../src/frontmatter.ts';
import { escapeLatex, toLatex } from '../src/latex.ts';
import type { Flavor } from '../src/types.ts';

const tex = (src: string, flavor: Flavor = 'academic'): string => {
  const { meta, body } = parseFrontmatter(src);
  return toLatex(buildMD(flavor, createFlavorDeps(hljs, katex)).parse(body, {}), { meta });
};

/** Just what sits between \begin{document} and \end{document}. */
const body = (src: string, flavor?: Flavor): string => {
  const out = tex(src, flavor);
  return out
    .slice(out.indexOf('\\begin{document}\n') + 16, out.lastIndexOf('\n\\end{document}'))
    .trim();
};

const BIB = [
  '```bibliography',
  '@book{knuth84, author = {Donald E. Knuth}, title = {The TeXbook}, year = 1984, url = {https://tex.org/a#b}}',
  '@misc{other, title = {Other}}',
  '```',
].join('\n');

describe('escapeLatex', () => {
  it('escapes the ten special characters', () => {
    expect(escapeLatex('\\ { } # $ % & _ ~ ^')).toBe(
      '\\textbackslash{} \\{ \\} \\# \\$ \\% \\& \\_ \\textasciitilde{} \\textasciicircum{}',
    );
  });

  it('spells symbols pdflatex lacks as commands and drops emoji', () => {
    expect(escapeLatex('✓ → ⌘K 🎉👍🏽 done')).toBe(
      '\\checkmark{} \\ensuremath{\\rightarrow} \\textsf{Cmd}K  done',
    );
  });
});

describe('toLatex — document', () => {
  it('writes a compilable skeleton with no title block when there is no title', () => {
    const out = tex('Just text.');
    expect(out).toMatch(/^% Generated by md-share/);
    expect(out).toContain('\\documentclass{article}');
    expect(out).toContain('\\ifPDFTeX');
    expect(out).not.toContain('\\maketitle');
    expect(body('Just text.')).toBe('Just text.');
  });

  it('takes the title, author, and date from frontmatter', () => {
    const out = tex('---\ntitle: A & B\nauthor: Ada\ndate: 2026\n---\n# Intro');
    expect(out).toContain('\\title{A \\& B}\n\\author{Ada}\n\\date{2026}');
    expect(out).toContain('\\maketitle');
    expect(body('---\ntitle: T\n---\n# Intro')).toBe(
      '\\maketitle\n\n\\section{Intro}\\label{intro}',
    );
  });

  it('uses a leading # heading as the title, and shifts the rest up', () => {
    const out = tex('# My *Paper*\n\n## One\n\n### Two\n\n###### Deep');
    expect(out).toContain('\\title{My \\emph{Paper}}\n\\author{}');
    expect(out).not.toContain('\\date');
    expect(out).toContain('\\section{One}\\label{one}');
    expect(out).toContain('\\subsection{Two}\\label{two}');
    expect(out).toContain('\\subparagraph{Deep}\\label{deep}');
  });

  it('leaves unlabelled a heading with nothing to slug, and numbers lists from 1 by default', () => {
    expect(body('Intro\n\n## 🎉\n\n1. one')).toBe(
      'Intro\n\n\\section{}\n\n\\begin{enumerate}\n\\item one\n\\end{enumerate}',
    );
  });

  it('handles an empty document', () => {
    expect(body('')).toBe('');
  });
});

describe('toLatex — inline', () => {
  it('maps emphasis, code, math, and breaks', () => {
    expect(body('**b** *i* ~~s~~ `a_b` $x^2$\nnext  \nhard', 'gfm')).toBe(
      '\\textbf{b} \\emph{i} \\sout{s} \\texttt{a\\_b} \\$x\\textasciicircum{}2\\$\nnext\\\\\nhard',
    );
    expect(body('$x^2$ and ==mark==', 'obsidian')).toBe('$x^2$ and \\hl{mark}');
  });

  it('links out with \\href and within with \\hyperref', () => {
    expect(body('[out](https://x.org/a%20b#c) [in](#sec)')).toBe(
      '\\href{https://x.org/a\\%20b\\#c}{out} \\hyperref[sec]{in}',
    );
  });

  it('includes local images and describes remote or embedded ones', () => {
    expect(body('![a](img/p.png) ![b](https://x.org/b.png) ![c](data:image/png;base64,AA)')).toBe(
      '\\includegraphics[width=\\linewidth,height=0.45\\textheight,keepaspectratio]{img/p.png} \\emph{[Image: b]} \\emph{[Image: c]}',
    );
  });

  it('puts footnote bodies in \\footnote and stops before the footnote list', () => {
    const out = body('Claim[^1].\n\n[^1]: A *note*\n    with two paragraphs.\n\n    Second.');
    expect(out).toBe('Claim\\footnote{A \\emph{note}\nwith two paragraphs. Second.}.');
  });

  it('keeps plugin text: tags, mentions, statuses, wikilinks; drops inline HTML', () => {
    expect(body('#tag [[Page]] a<br>b', 'obsidian')).toBe('\\#tag Page ab');
    expect(body('@alice {status:colour=Green|title=Done}', 'atlassian')).toBe(
      '@alice \\textbf{Done}',
    );
  });
});

describe('toLatex — citations and cross-references', () => {
  const doc = (text: string) =>
    body(`![P](p.png){#fig:p}\n\n$$ x $$ {#eq:x}\n\n${text}\n\n${BIB}`).split('\n\n')[2]!;

  it('cites sources, grouping plain ones into one \\cite', () => {
    expect(doc('[@knuth84; @other] [see @knuth84, p. 3; @other]')).toBe(
      '\\cite{knuth84,other} see \\cite[p. 3]{knuth84}, \\cite{other}',
    );
  });

  it('names narrative citations and refers to labels', () => {
    expect(doc('@knuth84 and @fig:p, [@eq:x; see @fig:p]')).toBe(
      'Knuth~\\cite{knuth84} and Figure~\\ref{fig:p}, Equation~\\eqref{eq:x}, see Figure~\\ref{fig:p}',
    );
  });

  it('marks what does not resolve, leaving plain @names as text', () => {
    expect(doc('[@nope] @fig:gone @someone')).toBe('\\textbf{?nope} \\textbf{?fig:gone} @someone');
  });

  it('writes figures, captioned tables, and labelled equations as floats', () => {
    const out = body(
      '![A *plot*](p.png){#fig:p}\n\n| a | b |\n|:-:|--:|\n| 1 | 2 |\n\n: Results {#tbl:r}\n\n$$ E = mc^2 $$ {#eq:e}',
    );
    expect(out).toContain(
      '\\begin{figure}[htbp]\n\\centering\n\\includegraphics[width=\\linewidth,height=0.45\\textheight,keepaspectratio]{p.png}\n\\caption{A \\emph{plot}}\\label{fig:p}\n\\end{figure}',
    );
    expect(out).toContain(
      '\\begin{table}[htbp]\n\\centering\n\\caption{Results}\\label{tbl:r}\n\\begin{tabular}{cr}\n\\hline\na & b \\\\\n\\hline\n1 & 2 \\\\\n\\hline\n\\end{tabular}\n\\end{table}',
    );
    expect(out).toContain('\\begin{equation}\\label{eq:e}\nE = mc^2\n\\end{equation}');
  });

  it('captions without a label, and leaves uncaptioned tables uncaptioned', () => {
    expect(body('| a |\n|---|\n| 1 |\n\nTable: Plain')).toContain(
      '\\caption{Plain}\n\\begin{tabular}{l}',
    );
    expect(body('| a |\n|---|')).toBe(
      '\\begin{table}[htbp]\n\\centering\n\\begin{tabular}{l}\n\\hline\na \\\\\n\\hline\n\\hline\n\\end{tabular}\n\\end{table}',
    );
  });

  it('writes the bibliography as thebibliography, under the document’s own heading', () => {
    const out = body(`[@knuth84]\n\n## References\n\n${BIB}`);
    expect(out).toContain(
      '\\begingroup\n\\renewcommand{\\section}[2]{}\n\\begin{thebibliography}{2}\n\\bibitem{knuth84} Donald E. Knuth. 1984. \\emph{The TeXbook.} \\url{https://tex.org/a\\#b}\n\\bibitem{other} \\emph{Other.}\n\\end{thebibliography}\n\\endgroup',
    );
    expect(body('```bibliography\nnothing\n```')).toBe('');
  });
});

describe('toLatex — blocks', () => {
  it('writes lists: bullets, numbering from a start, nesting, tasks, loose items', () => {
    expect(
      body('3. a\n4. b\n   - c\n\n- [ ] todo\n- [x] done\n\ntext\n\n- loose\n\n- items', 'gfm'),
    ).toBe(
      [
        '\\begin{enumerate}',
        '\\setcounter{enumi}{2}',
        '\\item a',
        '\\item b',
        '\\begin{itemize}',
        '\\item c',
        '\\end{itemize}',
        '',
        '\\end{enumerate}',
        '',
        '\\begin{itemize}',
        '\\item[$\\square$] todo',
        '\\item[$\\boxtimes$] done',
        '\\end{itemize}',
        '',
        'text',
        '',
        '\\begin{itemize}',
        '\\item loose',
        '',
        '\\item items',
        '',
        '\\end{itemize}',
      ].join('\n'),
    );
  });

  it('quotes blockquotes, callouts, and panels with their titles', () => {
    expect(body('> plain')).toBe('\\begin{quote}\nplain\n\n\\end{quote}');
    expect(body('> [!tip] Pro & tip\n> Body', 'obsidian')).toBe(
      '\\begin{quote}\n\\textbf{Pro \\& tip}\\par\nBody\n\n\\end{quote}',
    );
    expect(body('{info:title=Heads up}\nBody\n{info}', 'atlassian')).toContain(
      '\\begin{quote}\n\\textbf{Heads up}\\par\nBody',
    );
    expect(body('{note}\nBody\n{note}', 'atlassian')).toContain('\\textbf{note}\\par');
    expect(body('{expand:More}\nBody\n{expand}', 'atlassian')).toContain('\\textbf{More}\\par');
    expect(body('{expand}\nBody\n{expand}', 'atlassian')).toContain('\\textbf{Details}\\par');
  });

  it('writes definition lists as description', () => {
    expect(body('Term\n:   Meaning')).toBe(
      '\\begin{description}\n\\item[Term] Meaning\n\\end{description}',
    );
  });

  it('keeps code verbatim, noting Mermaid sources', () => {
    expect(body('```js\nconst a = 1; // 100%\n```\n\n    indented')).toBe(
      '\\begin{verbatim}\nconst a = 1; // 100%\n\\end{verbatim}\n\n\\begin{verbatim}\nindented\n\\end{verbatim}',
    );
    expect(body('```mermaid\ngraph TD\n```')).toMatch(/^% Mermaid diagram source/);
  });

  it('writes display math as equation*, or gather* for multi-line', () => {
    expect(body('$$\nx\n$$')).toBe('\\begin{equation*}\nx\n\\end{equation*}');
    expect(body('$$\na \\\\ b\n$$')).toBe('\\begin{gather*}\na \\\\ b\n\\end{gather*}');
    expect(body('$$\na \\\\ b\n$$ {#eq:ab}')).toBe(
      '\\begin{gather}\\label{eq:ab}\na \\\\ b\n\\end{gather}',
    );
    expect(body('$$\n\\begin{aligned} a \\\\ b \\end{aligned}\n$$')).toContain(
      '\\begin{equation*}',
    );
  });

  it('draws rules and comments out raw HTML', () => {
    expect(body('a\n\n---\n\n<div>\nraw\n</div>')).toBe(
      'a\n\n\\par\\noindent\\rule{\\linewidth}{0.4pt}\n\n% <div>\n% raw\n% </div>',
    );
  });
});
